package com.bean;

/**
 * Created by Vorringer on 2016/7/8.
 */
public class Order {
        // ------------------------
        // PRIVATE FIELDS
        // ------------------------

        // An autogenerated id (unique for each Order in the db)

        private long id;

        // The Order's client
        private long clientId;

        // The Order's shop

        private long shopId;

        // The Order's user

        private long userId;

        //The Order's longitude

        private double longitude;

        //The Order's latitude

        private double latitude;

        //The Order's status

        private short status;

        // ------------------------
        // PUBLIC METHODS
        // ------------------------

        public Order() { }

        public Order(long id) {
            this.id = id;
        }

        public Order(long clientId, long shopId,long userId,double longitude,double latitude,short status) {
            this.clientId= clientId;
            this.shopId = shopId;
            this.userId=userId;
            this.longitude = longitude;
            this.latitude = latitude;
            this.status = status;
        }
        public Order(double longitude,double latitude)
        {
            this.longitude=longitude;
            this.latitude=latitude;
        }

        // Getter and setter methods

        public long getId() {
            return id;
        }

        public void setId(long value) {
            this.id = value;
        }

        public long getClietnt() {
            return clientId;
        }

        public void setClient(long value) {
            this.clientId = value;
        }

        public long getShop() {
            return shopId;
        }

        public void setShop(long value) {
            this.shopId = value;
        }

        public long getUser() {
            return userId;
        }

        public void setUser(long value) {
            this.userId = value;
        }
        public double getLongitude() {
            return longitude;
        }

        public void setLongitude(double value) {
            this.longitude = value;
        }

        public double getLatitude() {
            return latitude;
        }

        public void setLatitude(double value) {
            this.latitude = value;
        }

        public long getStatus() {
            return status;
        }

        public void setStatus(short value) {
            this.status = value;
        }

    } // class Order

