package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Food
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "foods")
public class Food {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each Food in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The Food's name
  @NotNull
  private long orderId;
  
  // The Food's status
  @NotNull
  private long itemId;
  
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Food() { }

  public Food(long id) { 
    this.id = id;
  }
  
  public Food(long orderId,long itemId){
    this.orderId = orderId;
    this.itemId = itemId;
  }

  // Getter and setter methods

  public long getId(){
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public long getOrderId() {
    return orderId;
  }
  
  public void setOrderId(long value) {
    this.orderId = orderId;
  }
  
  public long getItemId() {
	    return itemId;
	  }
  
	 public void setItemId(long value) {
	    this.itemId = itemId;
	  }
  
  
} // class Food

