package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Message 
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "messages")
public class Message {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each Message in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
   
  //The Message's status
  @NotNull
  private short status;
  
//The Message's info
  @NotNull
  private String info;
  
//The Message's time
  @NotNull
  private String time;
  
//The Message's from
  @NotNull
  private long sender;
  
//The Message's from
  @NotNull
  private String senderName;
  
  
//The Message's to
  @NotNull
  private long receiver;
  
//The Message's to
  @NotNull
  private String receiverName;
  
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Message() { }

  public Message(long id) { 
    this.id = id;
  }
  
  public Message(short status,String info,String time,long sender,String senderName,long receiver,String receiverName) {
    this.status = status;
    this.info=info;
    this.time=time;
    this.sender=sender;
    this.senderName=senderName;
    this.receiver=receiver; 
    this.receiverName=receiverName;
  }

  // Getter and setter methods

  
  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  

  public short getStatus() {
    return status;
  }

  public void setStatus(short value) {
    this.status = value;
  }
  
  public String getInfo() {
	    return info;
	  }

	  public void setInfo(String value) {
	    this.info = value;
	  }
	  
   public String getTime() {
		    return time;
		  }

	public void setTime(String value) {
		    this.time = value;
		  }
	
	  public String getSenderName() {
		    return senderName;
		  }

	public void setSenderName(String value) {
		    this.senderName = value;
		  }
	
	  public String getReceiverName() {
		    return receiverName;
		  }

	public void setReceiverName(String value) {
		    this.receiverName = value;
		  }
	
	
	  
 public long getReceiver() {
		    return receiver;		  }

	public void setReceiver(long value) {
		    this.receiver = value;
		  }
	  
    public long getSender() {
		    return sender;
		  }

    public void setSender(long value) {
		    this.sender = value;
		  }
    
      
} // class Message


