package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "users")
public class User {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's phone
  @NotNull
  private String phone;
  
  // The user's name
  @NotNull
  private String name;
  
  //The user's status
  @NotNull
  private short status;
  
  //The user's shop
  @NotNull
  private long shopId;
  
  //The user's password
  @NotNull
  private String password;
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String phone, String name,long shopId,String password,short status){
    this.phone = phone;
    this.name = name;
    this.shopId = shopId;
    this.password = password;
    this.status = status;
  }

  // Getter and setter methods

  public long getId(){
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getPhone() {
    return phone;
  }
  
  public void setPhone(String value) {
    this.phone = value;
  }
  
  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }
  
  public long getShopId() {
	    return shopId;
	  }

  public void setShopId(long value) {
	    this.shopId = value;
	  }

  public String getPassword() {
	    return password;
	  }
	  
  public void setPassword(String value) {
	    this.password = value;
	  }
  
  public short getStatus() {
	    return status;
  }

  public void setStatus(short value) {
	    this.status = value;
  }
	  
  
} // class User
